### ISSUE TITLE
小小建议

### ISSUE THREAD

**Issue by error0g** [cn-cerc/summer-server#207]
虽然面试没过，但的确想参与这个框架开发。😬

这算个人的小小建议哈 今天有幸能看到现场一位小哥新人培训
page里面的HTML标签可以封装为java对象，而不是书写字符串的html代码 这样不好的表现有 阅读“魔法值”不方便，还有经常有字符串转义问题。封装以后完全可以像写java代码一样书写前端。

**Comment by itjun** [comment]
非常感谢您的建议，我们最近在3.x的版本上重构了代码，现在支持直接使用java对象操作html元素了。
